# .github/workflows/main.yml
name: Automation CI Pipeline (E2E)

# Define cuándo debe ejecutarse el flujo de trabajo (en push o pull request a 'main')
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# --- EL JOB (TRABAJO) ---
jobs:
  run-automation-tests:
    # Indica que este trabajo se ejecutará en un servidor Linux (Ubuntu)
    runs-on: ubuntu-latest

    # --- LOS STEPS (PASOS) ---
    steps:
    - name: 1. Checkout Code
      uses: actions/checkout@v3

    - name: 2. Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: 3. Install Dependencies
      run: |
        # Navega a la carpeta de tu proyecto E2E
        cd 01-web-e2e-saucedemo
        # Instala Selenium y otros requisitos
        pip install -r requirements.txt

    - name: 4. Run Web E2E Tests
      run: |
        # Navega a la carpeta del proyecto
        cd 01-web-e2e-saucedemo
        # ESTE ES EL COMANDO CLAVE: ejecuta todos los tests encontrados en la carpeta 'tests'
        python -m unittest discover tests
